project_id = "rriizlxqfpfpdflgxjtj"

[functions.generate-bot-avatar]
verify_jwt = false

[functions.create-org-user]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-multiattendant-webhook]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = false

[functions.whatsapp-create-upload-url]
verify_jwt = false

[functions.whatsapp-media-proxy]
verify_jwt = false

[functions.zapi-assistant-webhook]
verify_jwt = false

[functions.evolution-assistant-webhook]
verify_jwt = false

[functions.evolution-send-message]
verify_jwt = false

[functions.evolution-instance-manager]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.ai-bot-process]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.manual-user-provision]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.add-subscription-item]
verify_jwt = false

[functions.integration-webhook]
verify_jwt = false

[functions.webhook-proxy]
verify_jwt = false
